params:  
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: True
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: variance_scaling_initializer
          scale: 0.02
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 128, 64]
      activation: elu
      initializer:
        name: variance_scaling_initializer
        scale: 2
      regularizer:
        name:  'None' #'l2_regularizer'
        #scale: 0.001

  load_checkpoint: False
  load_path: path

  config:
      reward_shaper:
        scale_value: 0.1
      normalize_advantage: True
      gamma: 0.99
      tau: 0.9

      learning_rate: 3e-4
      name: supercreature
      score_to_win: 30000

      grad_norm: 0.5
      entropy_coef: 0.0
      truncate_grads: True
      env_name:  openai_gym
      ppo: true
      e_clip: 0.2
      clip_value: True
      num_actors: 32
      steps_num: 1024
      minibatch_size: 16384
      mini_epochs: 16
      critic_coef: 1
      lr_schedule:  adaptive
      lr_threshold: 0.008

      normalize_input: True
      seq_len: 8
      bounds_loss_coef: 0.001
      env_config:
        name: gym_supercreature:supercreature-v0
